name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: pwsh
      run: |
        $tag = "aspnet48sample:latest"
        docker build --tag $tag .
        echo $GITHUB_TOKEN| docker login ghcr.io -u pbering --password-stdin
        docker push $tag
