name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        shell: pwsh
        run: |
          $tag = "ghcr.io/pbering/aspnet48sample:1.0-ltsc2019"
          docker build --tag $tag .
          docker push $tag
